[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "API"
version = "0.1.0"
description = "Your project description"
authors = [
    { name="admin", email="admin@growwstacks.com" }
]
